import { mkdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { join, relative, resolve } from "node:path";

import type * as TS from "typescript";

const ts = createRequire(import.meta.url)("typescript") as typeof TS;

const REPO_ROOT = resolve(import.meta.dir, "../../..");
const API_ROOT = join(REPO_ROOT, "apps/api");
const SRC_ROOT = join(API_ROOT, "src");

const isModelFile = (path: string): boolean =>
  path.endsWith(".model.ts") || /\/dto\/[^/]+\.dto\.ts$/.test(path);

const loadProgram = () => {
  const configPath = join(API_ROOT, "tsconfig.json");
  const config = ts.readConfigFile(configPath, ts.sys.readFile);

  if (config.error) {
    throw new Error(
      ts.flattenDiagnosticMessageText(config.error.messageText, "\n"),
    );
  }

  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, API_ROOT);

  return ts.createProgram(parsed.fileNames, parsed.options);
};

const FORMAT_FLAGS =
  ts.TypeFormatFlags.NoTruncation |
  ts.TypeFormatFlags.InTypeAlias |
  ts.TypeFormatFlags.UseFullyQualifiedType;

const formatMembers = (rendered: string): string | undefined => {
  const trimmed = rendered.trim();

  if (!trimmed.startsWith("{") || !trimmed.endsWith("}")) return undefined;

  const body = trimmed.slice(1, -1).trim();

  if (body.length === 0) return "";

  return body
    .split(";")
    .map((member) => member.trim())
    .filter((member) => member.length > 0)
    .map((member) => `  ${member};`)
    .join("\n");
};

const collect = (program: ReturnType<typeof loadProgram>) => {
  const checker = program.getTypeChecker();
  const files = new Map<string, string[]>();

  for (const source of program.getSourceFiles()) {
    if (source.isDeclarationFile) continue;
    if (!source.fileName.startsWith(SRC_ROOT)) continue;
    if (!isModelFile(source.fileName)) continue;

    const moduleSymbol = checker.getSymbolAtLocation(source);

    if (!moduleSymbol) continue;

    const blocks: string[] = [];

    for (const exported of checker.getExportsOfModule(moduleSymbol)) {
      const declared = checker.getDeclaredTypeOfSymbol(exported);
      const rendered = checker.typeToString(declared, undefined, FORMAT_FLAGS);
      const members = formatMembers(rendered);

      if (members === undefined) continue;

      const name = exported.getName();

      blocks.push(
        members.length === 0
          ? `export interface ${name} {}`
          : `export interface ${name} {\n${members}\n}`,
      );
    }

    if (blocks.length > 0) {
      files.set(relative(SRC_ROOT, source.fileName), blocks);
    }
  }

  return files;
};

const HEADER = `// Generated by \`bun run generate\`. Do not edit.\n`;

const main = async () => {
  const outDir = process.argv[2]
    ? resolve(process.cwd(), process.argv[2])
    : resolve(REPO_ROOT, "packages/api-client/src/generated");
  const files = collect(loadProgram());

  if (files.size === 0) {
    throw new Error("no model or dto exports found");
  }

  const sorted = [...files.entries()].sort(([a], [b]) => a.localeCompare(b));
  const sections = sorted.map(
    ([path, blocks]) => `// ${path}\n${blocks.join("\n\n")}`,
  );

  await mkdir(outDir, { recursive: true });
  await writeFile(
    join(outDir, "models.ts"),
    `${HEADER}\n${sections.join("\n\n")}\n`,
  );

  console.warn(
    `generated ${sorted.reduce((n, [, b]) => n + b.length, 0)} types from ${files.size} files`,
  );
};

await main();
